server:
 port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/bootdb
    username: root
    password: root
  jpa:
    profiles: container
    hibernate:
     ddl-auto: create-drop
     org:
       hibernate:
         dialect:
           MySQL8Dialect:
    generate-ddl: true